name: Deploy_GHRunner_Linux_ACI

on:
  workflow_dispatch:

jobs:
  deploy-gh-runner-aci:
    runs-on: ubuntu-latest
    steps:
      # checkout the repo
      - name: 'Checkout GitHub Action'
        uses: actions/checkout@main

      - name: 'Login via Azure CLI'
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: 'Deploy to Azure Container Instances'
        uses: 'azure/aci-deploy@v1'
        with:
          resource-group: 'runners-rg'
          image: 'kmiszelacr.azurecr.io/github-runner-lin:2.320.0'
          registry-login-server: 'kmiszelacr.azurecr.io'
          registry-username: ${{ secrets.REGISTRY_USERNAME }}
          registry-password: ${{ secrets.REGISTRY_PASSWORD }}
          name: 'gh-runner-linux-01'
          dns-name-label: 'kmiszel187'
          environment-variables: GH_TOKEN=${{ secrets.PAT_TOKEN }} GH_OWNER='MISZELorg'
          location: 'northeurope'

          ##not working. Error: Error: Encountered an internal server error. The tracking activity id is '47dd76d2-5e57-4c8b-9ae6-c56f1d312448', correlation id is '991e9a02-ff1e-4d18-9f02-10398b254abd'.